-- --------------------------------------------------------
-- Hôte:                         localhost
-- Version du serveur:           8.0.30 - MySQL Community Server - GPL
-- SE du serveur:                Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Listage de la structure de table information_schema. INNODB_BUFFER_POOL_STATS
CREATE TEMPORARY TABLE IF NOT EXISTS `INNODB_BUFFER_POOL_STATS` (
  `POOL_ID` bigint unsigned NOT NULL DEFAULT '0',
  `POOL_SIZE` bigint unsigned NOT NULL DEFAULT '0',
  `FREE_BUFFERS` bigint unsigned NOT NULL DEFAULT '0',
  `DATABASE_PAGES` bigint unsigned NOT NULL DEFAULT '0',
  `OLD_DATABASE_PAGES` bigint unsigned NOT NULL DEFAULT '0',
  `MODIFIED_DATABASE_PAGES` bigint unsigned NOT NULL DEFAULT '0',
  `PENDING_DECOMPRESS` bigint unsigned NOT NULL DEFAULT '0',
  `PENDING_READS` bigint unsigned NOT NULL DEFAULT '0',
  `PENDING_FLUSH_LRU` bigint unsigned NOT NULL DEFAULT '0',
  `PENDING_FLUSH_LIST` bigint unsigned NOT NULL DEFAULT '0',
  `PAGES_MADE_YOUNG` bigint unsigned NOT NULL DEFAULT '0',
  `PAGES_NOT_MADE_YOUNG` bigint unsigned NOT NULL DEFAULT '0',
  `PAGES_MADE_YOUNG_RATE` double NOT NULL DEFAULT '0',
  `PAGES_MADE_NOT_YOUNG_RATE` double NOT NULL DEFAULT '0',
  `NUMBER_PAGES_READ` bigint unsigned NOT NULL DEFAULT '0',
  `NUMBER_PAGES_CREATED` bigint unsigned NOT NULL DEFAULT '0',
  `NUMBER_PAGES_WRITTEN` bigint unsigned NOT NULL DEFAULT '0',
  `PAGES_READ_RATE` double NOT NULL DEFAULT '0',
  `PAGES_CREATE_RATE` double NOT NULL DEFAULT '0',
  `PAGES_WRITTEN_RATE` double NOT NULL DEFAULT '0',
  `NUMBER_PAGES_GET` bigint unsigned NOT NULL DEFAULT '0',
  `HIT_RATE` bigint unsigned NOT NULL DEFAULT '0',
  `YOUNG_MAKE_PER_THOUSAND_GETS` bigint unsigned NOT NULL DEFAULT '0',
  `NOT_YOUNG_MAKE_PER_THOUSAND_GETS` bigint unsigned NOT NULL DEFAULT '0',
  `NUMBER_PAGES_READ_AHEAD` bigint unsigned NOT NULL DEFAULT '0',
  `NUMBER_READ_AHEAD_EVICTED` bigint unsigned NOT NULL DEFAULT '0',
  `READ_AHEAD_RATE` double NOT NULL DEFAULT '0',
  `READ_AHEAD_EVICTED_RATE` double NOT NULL DEFAULT '0',
  `LRU_IO_TOTAL` bigint unsigned NOT NULL DEFAULT '0',
  `LRU_IO_CURRENT` bigint unsigned NOT NULL DEFAULT '0',
  `UNCOMPRESS_TOTAL` bigint unsigned NOT NULL DEFAULT '0',
  `UNCOMPRESS_CURRENT` bigint unsigned NOT NULL DEFAULT '0'
) ENGINE=MEMORY DEFAULT CHARSET=utf8mb3;

-- Listage des données de la table information_schema.INNODB_BUFFER_POOL_STATS : 0 rows
/*!40000 ALTER TABLE `INNODB_BUFFER_POOL_STATS` DISABLE KEYS */;
INSERT INTO `INNODB_BUFFER_POOL_STATS` (`POOL_ID`, `POOL_SIZE`, `FREE_BUFFERS`, `DATABASE_PAGES`, `OLD_DATABASE_PAGES`, `MODIFIED_DATABASE_PAGES`, `PENDING_DECOMPRESS`, `PENDING_READS`, `PENDING_FLUSH_LRU`, `PENDING_FLUSH_LIST`, `PAGES_MADE_YOUNG`, `PAGES_NOT_MADE_YOUNG`, `PAGES_MADE_YOUNG_RATE`, `PAGES_MADE_NOT_YOUNG_RATE`, `NUMBER_PAGES_READ`, `NUMBER_PAGES_CREATED`, `NUMBER_PAGES_WRITTEN`, `PAGES_READ_RATE`, `PAGES_CREATE_RATE`, `PAGES_WRITTEN_RATE`, `NUMBER_PAGES_GET`, `HIT_RATE`, `YOUNG_MAKE_PER_THOUSAND_GETS`, `NOT_YOUNG_MAKE_PER_THOUSAND_GETS`, `NUMBER_PAGES_READ_AHEAD`, `NUMBER_READ_AHEAD_EVICTED`, `READ_AHEAD_RATE`, `READ_AHEAD_EVICTED_RATE`, `LRU_IO_TOTAL`, `LRU_IO_CURRENT`, `UNCOMPRESS_TOTAL`, `UNCOMPRESS_CURRENT`) VALUES
	(0, 8191, 6797, 1379, 497, 90, 0, 0, 0, 0, 1, 0, 0, 0, 1148, 231, 407, 2.8260748873388777, 12.434729504291061, 2.8260748873388777, 70878, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
/*!40000 ALTER TABLE `INNODB_BUFFER_POOL_STATS` ENABLE KEYS */;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
