-- --------------------------------------------------------
-- Hôte:                         localhost
-- Version du serveur:           8.0.30 - MySQL Community Server - GPL
-- SE du serveur:                Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Listage de la structure de table information_schema. TABLE_CONSTRAINTS_EXTENSIONS
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql.infoschema`@`localhost` SQL SECURITY DEFINER VIEW `information_schema`.`TABLE_IF NOT EXISTS CONSTRAINTS_EXTENSIONS` AS select `cat`.`name` AS `CONSTRAINT_CATALOG`,`sch`.`name` AS `CONSTRAINT_SCHEMA`,`idx`.`name` AS `CONSTRAINT_NAME`,`tbl`.`name` AS `TABLE_NAME`,`idx`.`engine_attribute` AS `ENGINE_ATTRIBUTE`,`idx`.`secondary_engine_attribute` AS `SECONDARY_ENGINE_ATTRIBUTE` from (((`mysql`.`indexes` `idx` join `mysql`.`tables` `tbl` on((`idx`.`table_id` = `tbl`.`id`))) join `mysql`.`schemata` `sch` on((`tbl`.`schema_id` = `sch`.`id`))) join `mysql`.`catalogs` `cat` on((`cat`.`id` = `sch`.`catalog_id`))) where ((0 <> can_access_table(`sch`.`name`,`tbl`.`name`)) and (0 <> is_visible_dd_object(`tbl`.`hidden`,false,`idx`.`options`)));

-- Listage des données de la table information_schema.TABLE_CONSTRAINTS_EXTENSIONS : 0 rows
/*!40000 ALTER TABLE `TABLE_CONSTRAINTS_EXTENSIONS` DISABLE KEYS */;
INSERT INTO `TABLE_CONSTRAINTS_EXTENSIONS` (`CONSTRAINT_CATALOG`, `CONSTRAINT_SCHEMA`, `CONSTRAINT_NAME`, `TABLE_NAME`, `ENGINE_ATTRIBUTE`, `SECONDARY_ENGINE_ATTRIBUTE`) VALUES
	('def', 'mysql', 'PRIMARY', 'innodb_table_stats', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'innodb_index_stats', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'cond_instances', NULL, NULL),
	('def', 'performance_schema', 'NAME', 'cond_instances', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'error_log', NULL, NULL),
	('def', 'performance_schema', 'THREAD_ID', 'error_log', NULL, NULL),
	('def', 'performance_schema', 'PRIO', 'error_log', NULL, NULL),
	('def', 'performance_schema', 'ERROR_CODE', 'error_log', NULL, NULL),
	('def', 'performance_schema', 'SUBSYSTEM', 'error_log', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_waits_current', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_waits_history', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'events_waits_summary_by_host_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_waits_summary_by_instance', NULL, NULL),
	('def', 'performance_schema', 'EVENT_NAME', 'events_waits_summary_by_instance', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_waits_summary_by_thread_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'USER', 'events_waits_summary_by_user_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'ACCOUNT', 'events_waits_summary_by_account_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_waits_summary_global_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'file_instances', NULL, NULL),
	('def', 'performance_schema', 'EVENT_NAME', 'file_instances', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'file_summary_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'file_summary_by_instance', NULL, NULL),
	('def', 'performance_schema', 'FILE_NAME', 'file_summary_by_instance', NULL, NULL),
	('def', 'performance_schema', 'EVENT_NAME', 'file_summary_by_instance', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'host_cache', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'host_cache', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'mutex_instances', NULL, NULL),
	('def', 'performance_schema', 'NAME', 'mutex_instances', NULL, NULL),
	('def', 'performance_schema', 'LOCKED_BY_THREAD_ID', 'mutex_instances', NULL, NULL),
	('def', 'performance_schema', 'OBJECT', 'objects_summary_global_by_type', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'processlist', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'rwlock_instances', NULL, NULL),
	('def', 'performance_schema', 'NAME', 'rwlock_instances', NULL, NULL),
	('def', 'performance_schema', 'WRITE_LOCKED_BY_THREAD_ID', 'rwlock_instances', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'setup_actors', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'setup_consumers', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'setup_instruments', NULL, NULL),
	('def', 'performance_schema', 'OBJECT', 'setup_objects', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'setup_threads', NULL, NULL),
	('def', 'performance_schema', 'OBJECT', 'table_io_waits_summary_by_index_usage', NULL, NULL),
	('def', 'performance_schema', 'OBJECT', 'table_io_waits_summary_by_table', NULL, NULL),
	('def', 'performance_schema', 'OBJECT', 'table_lock_waits_summary_by_table', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'threads', NULL, NULL),
	('def', 'performance_schema', 'PROCESSLIST_ID', 'threads', NULL, NULL),
	('def', 'performance_schema', 'THREAD_OS_ID', 'threads', NULL, NULL),
	('def', 'performance_schema', 'NAME', 'threads', NULL, NULL),
	('def', 'performance_schema', 'PROCESSLIST_ACCOUNT', 'threads', NULL, NULL),
	('def', 'performance_schema', 'PROCESSLIST_HOST', 'threads', NULL, NULL),
	('def', 'performance_schema', 'RESOURCE_GROUP', 'threads', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_stages_current', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_stages_history', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_stages_summary_by_thread_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'ACCOUNT', 'events_stages_summary_by_account_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'USER', 'events_stages_summary_by_user_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'events_stages_summary_by_host_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_stages_summary_global_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_statements_current', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_statements_history', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_statements_summary_by_thread_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'ACCOUNT', 'events_statements_summary_by_account_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'USER', 'events_statements_summary_by_user_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'events_statements_summary_by_host_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_statements_summary_global_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'SCHEMA_NAME', 'events_statements_summary_by_digest', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_statements_summary_by_program', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_statements_histogram_global', NULL, NULL),
	('def', 'performance_schema', 'SCHEMA_NAME', 'events_statements_histogram_by_digest', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_transactions_current', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_transactions_history', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_transactions_summary_by_thread_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'ACCOUNT', 'events_transactions_summary_by_account_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'USER', 'events_transactions_summary_by_user_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'events_transactions_summary_by_host_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'events_transactions_summary_global_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'USER', 'events_errors_summary_by_user_by_error', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'events_errors_summary_by_host_by_error', NULL, NULL),
	('def', 'performance_schema', 'ACCOUNT', 'events_errors_summary_by_account_by_error', NULL, NULL),
	('def', 'performance_schema', 'THREAD_ID', 'events_errors_summary_by_thread_by_error', NULL, NULL),
	('def', 'performance_schema', 'ERROR_NUMBER', 'events_errors_summary_global_by_error', NULL, NULL),
	('def', 'performance_schema', 'USER', 'users', NULL, NULL),
	('def', 'performance_schema', 'ACCOUNT', 'accounts', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'hosts', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'socket_instances', NULL, NULL),
	('def', 'performance_schema', 'THREAD_ID', 'socket_instances', NULL, NULL),
	('def', 'performance_schema', 'SOCKET_ID', 'socket_instances', NULL, NULL),
	('def', 'performance_schema', 'IP', 'socket_instances', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'socket_summary_by_instance', NULL, NULL),
	('def', 'performance_schema', 'EVENT_NAME', 'socket_summary_by_instance', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'socket_summary_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'session_connect_attrs', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'session_account_connect_attrs', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'memory_summary_global_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'ACCOUNT', 'memory_summary_by_account_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'memory_summary_by_host_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'memory_summary_by_thread_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'USER', 'memory_summary_by_user_by_event_name', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'table_handles', NULL, NULL),
	('def', 'performance_schema', 'OBJECT_TYPE', 'table_handles', NULL, NULL),
	('def', 'performance_schema', 'OWNER_THREAD_ID', 'table_handles', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'metadata_locks', NULL, NULL),
	('def', 'performance_schema', 'OBJECT_TYPE', 'metadata_locks', NULL, NULL),
	('def', 'performance_schema', 'OWNER_THREAD_ID', 'metadata_locks', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'data_locks', NULL, NULL),
	('def', 'performance_schema', 'ENGINE_TRANSACTION_ID', 'data_locks', NULL, NULL),
	('def', 'performance_schema', 'THREAD_ID', 'data_locks', NULL, NULL),
	('def', 'performance_schema', 'OBJECT_SCHEMA', 'data_locks', NULL, NULL),
	('def', 'performance_schema', 'REQUESTING_ENGINE_LOCK_ID', 'data_lock_waits', NULL, NULL),
	('def', 'performance_schema', 'BLOCKING_ENGINE_LOCK_ID', 'data_lock_waits', NULL, NULL),
	('def', 'performance_schema', 'REQUESTING_ENGINE_TRANSACTION_ID', 'data_lock_waits', NULL, NULL),
	('def', 'performance_schema', 'BLOCKING_ENGINE_TRANSACTION_ID', 'data_lock_waits', NULL, NULL),
	('def', 'performance_schema', 'REQUESTING_THREAD_ID', 'data_lock_waits', NULL, NULL),
	('def', 'performance_schema', 'BLOCKING_THREAD_ID', 'data_lock_waits', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'replication_connection_configuration', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'replication_connection_status', NULL, NULL),
	('def', 'performance_schema', 'THREAD_ID', 'replication_connection_status', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'replication_applier_configuration', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'replication_applier_status', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'replication_applier_status_by_coordinator', NULL, NULL),
	('def', 'performance_schema', 'THREAD_ID', 'replication_applier_status_by_coordinator', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'replication_applier_status_by_worker', NULL, NULL),
	('def', 'performance_schema', 'THREAD_ID', 'replication_applier_status_by_worker', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'prepared_statements_instances', NULL, NULL),
	('def', 'performance_schema', 'OWNER_THREAD_ID', 'prepared_statements_instances', NULL, NULL),
	('def', 'performance_schema', 'STATEMENT_ID', 'prepared_statements_instances', NULL, NULL),
	('def', 'performance_schema', 'STATEMENT_NAME', 'prepared_statements_instances', NULL, NULL),
	('def', 'performance_schema', 'OWNER_OBJECT_TYPE', 'prepared_statements_instances', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'user_variables_by_thread', NULL, NULL),
	('def', 'performance_schema', 'ACCOUNT', 'status_by_account', NULL, NULL),
	('def', 'performance_schema', 'HOST', 'status_by_host', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'status_by_thread', NULL, NULL),
	('def', 'performance_schema', 'USER', 'status_by_user', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'global_status', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'session_status', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'variables_by_thread', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'global_variables', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'session_variables', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'persisted_variables', NULL, NULL),
	('def', 'performance_schema', 'PRIMARY', 'user_defined_functions', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'db', NULL, NULL),
	('def', 'mysql', 'User', 'db', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'user', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'default_roles', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'role_edges', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'global_grants', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'password_history', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'func', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'plugin', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'help_topic', NULL, NULL),
	('def', 'mysql', 'name', 'help_topic', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'help_category', NULL, NULL),
	('def', 'mysql', 'name', 'help_category', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'help_relation', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'servers', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'tables_priv', NULL, NULL),
	('def', 'mysql', 'Grantor', 'tables_priv', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'columns_priv', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'help_keyword', NULL, NULL),
	('def', 'mysql', 'name', 'help_keyword', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'time_zone_name', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'time_zone', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'time_zone_transition', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'time_zone_transition_type', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'time_zone_leap_second', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'procs_priv', NULL, NULL),
	('def', 'mysql', 'Grantor', 'procs_priv', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'component', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'slave_relay_log_info', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'slave_master_info', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'slave_worker_info', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'gtid_executed', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'replication_asynchronous_connection_failover', NULL, NULL),
	('def', 'mysql', 'Channel_name', 'replication_asynchronous_connection_failover', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'replication_asynchronous_connection_failover_managed', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'replication_group_member_actions', NULL, NULL),
	('def', 'mysql', 'event', 'replication_group_member_actions', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'replication_group_configuration_version', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'server_cost', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'engine_cost', NULL, NULL),
	('def', 'mysql', 'PRIMARY', 'proxies_priv', NULL, NULL),
	('def', 'mysql', 'Grantor', 'proxies_priv', NULL, NULL),
	('def', 'sys', 'PRIMARY', 'sys_config', NULL, NULL),
	('def', 'employes', 'PRIMARY', 'dept', NULL, NULL),
	('def', 'employes', 'PRIMARY', 'projet', NULL, NULL),
	('def', 'employes', 'PRIMARY', 'emp', NULL, NULL),
	('def', 'employes', 'FK_DEPTNO', 'emp', NULL, NULL),
	('def', 'employes', 'FK_MGR', 'emp', NULL, NULL),
	('def', 'tp1', 'PRIMARY', 'livre', NULL, NULL),
	('def', 'tp1', 'PRIMARY', 'exemplaire', NULL, NULL),
	('def', 'guide', 'PRIMARY', 'restaurants', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'categories', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'departements', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'habilitations', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'images', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'proprietaires', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'association_img', NULL, NULL),
	('def', 'immochateau', 'FK_img', 'association_img', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'biens_immobiliers', NULL, NULL),
	('def', 'immochateau', 'id_utilisateur_commercial', 'biens_immobiliers', NULL, NULL),
	('def', 'immochateau', 'id_categorie', 'biens_immobiliers', NULL, NULL),
	('def', 'immochateau', 'fK_proprietaire', 'biens_immobiliers', NULL, NULL),
	('def', 'immochateau', 'fk_departement', 'biens_immobiliers', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'documents', NULL, NULL),
	('def', 'immochateau', 'id', 'documents', NULL, NULL),
	('def', 'immochateau', 'PRIMARY', 'utilisateurs', NULL, NULL),
	('def', 'immochateau', 'id_niveau', 'utilisateurs', NULL, NULL),
	('def', 'voiliers', 'PRIMARY', 'utilisateurs', NULL, NULL),
	('def', 'voiliers', 'PRIMARY', 'candidats', NULL, NULL),
	('def', 'festival', 'PRIMARY', 'departements', NULL, NULL),
	('def', 'festival', 'PRIMARY', 'candidats', NULL, NULL),
	('def', 'festival', 'Fk_departement_user', 'candidats', NULL, NULL);
/*!40000 ALTER TABLE `TABLE_CONSTRAINTS_EXTENSIONS` ENABLE KEYS */;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
