-- --------------------------------------------------------
-- Hôte:                         localhost
-- Version du serveur:           8.0.30 - MySQL Community Server - GPL
-- SE du serveur:                Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Listage de la structure de table information_schema. TABLE_CONSTRAINTS
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql.infoschema`@`localhost` SQL SECURITY DEFINER VIEW `information_schema`.`TABLE_IF NOT EXISTS CONSTRAINTS` AS select (`cat`.`name` collate utf8mb3_tolower_ci) AS `CONSTRAINT_CATALOG`,(`sch`.`name` collate utf8mb3_tolower_ci) AS `CONSTRAINT_SCHEMA`,`constraints`.`CONSTRAINT_NAME` AS `CONSTRAINT_NAME`,(`sch`.`name` collate utf8mb3_tolower_ci) AS `TABLE_SCHEMA`,(`tbl`.`name` collate utf8mb3_tolower_ci) AS `TABLE_NAME`,`constraints`.`CONSTRAINT_TYPE` AS `CONSTRAINT_TYPE`,`constraints`.`ENFORCED` AS `ENFORCED` from (((`mysql`.`tables` `tbl` join `mysql`.`schemata` `sch` on((`tbl`.`schema_id` = `sch`.`id`))) join `mysql`.`catalogs` `cat` on((`cat`.`id` = `sch`.`catalog_id`))) join lateral (select `idx`.`name` AS `CONSTRAINT_NAME`,if((`idx`.`type` = 'PRIMARY'),'PRIMARY KEY',`idx`.`type`) AS `CONSTRAINT_TYPE`,'YES' AS `ENFORCED` from `mysql`.`indexes` `idx` where ((`idx`.`table_id` = `tbl`.`id`) and (`idx`.`type` in ('PRIMARY','UNIQUE')) and (0 <> is_visible_dd_object(`tbl`.`hidden`,`idx`.`hidden`,`idx`.`options`))) union all select (`fk`.`name` collate utf8mb3_tolower_ci) AS `CONSTRAINT_NAME`,'FOREIGN KEY' AS `CONSTRAINT_TYPE`,'YES' AS `ENFORCED` from `mysql`.`foreign_keys` `fk` where (`fk`.`table_id` = `tbl`.`id`) union all select `cc`.`name` AS `CONSTRAINT_NAME`,'CHECK' AS `CONSTRAINT_TYPE`,`cc`.`enforced` AS `ENFORCED` from `mysql`.`check_constraints` `cc` where (`cc`.`table_id` = `tbl`.`id`)) `constraints`) where ((0 <> can_access_table(`sch`.`name`,`tbl`.`name`)) and (0 <> is_visible_dd_object(`tbl`.`hidden`)));

-- Listage des données de la table information_schema.TABLE_CONSTRAINTS : 0 rows
/*!40000 ALTER TABLE `TABLE_CONSTRAINTS` DISABLE KEYS */;
INSERT INTO `TABLE_CONSTRAINTS` (`CONSTRAINT_CATALOG`, `CONSTRAINT_SCHEMA`, `CONSTRAINT_NAME`, `TABLE_SCHEMA`, `TABLE_NAME`, `CONSTRAINT_TYPE`, `ENFORCED`) VALUES
	('def', 'mysql', 'PRIMARY', 'mysql', 'innodb_table_stats', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'innodb_index_stats', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'cond_instances', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'error_log', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_waits_current', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_waits_history', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'HOST', 'performance_schema', 'events_waits_summary_by_host_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_waits_summary_by_instance', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_waits_summary_by_thread_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'USER', 'performance_schema', 'events_waits_summary_by_user_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'ACCOUNT', 'performance_schema', 'events_waits_summary_by_account_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_waits_summary_global_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'file_instances', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'file_summary_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'file_summary_by_instance', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'host_cache', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'mutex_instances', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'OBJECT', 'performance_schema', 'objects_summary_global_by_type', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'processlist', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'rwlock_instances', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'setup_actors', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'setup_consumers', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'setup_instruments', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'OBJECT', 'performance_schema', 'setup_objects', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'setup_threads', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'OBJECT', 'performance_schema', 'table_io_waits_summary_by_index_usage', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'OBJECT', 'performance_schema', 'table_io_waits_summary_by_table', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'OBJECT', 'performance_schema', 'table_lock_waits_summary_by_table', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'threads', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_stages_current', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_stages_history', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_stages_summary_by_thread_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'ACCOUNT', 'performance_schema', 'events_stages_summary_by_account_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'USER', 'performance_schema', 'events_stages_summary_by_user_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'HOST', 'performance_schema', 'events_stages_summary_by_host_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_stages_summary_global_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_statements_current', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_statements_history', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_statements_summary_by_thread_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'ACCOUNT', 'performance_schema', 'events_statements_summary_by_account_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'USER', 'performance_schema', 'events_statements_summary_by_user_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'HOST', 'performance_schema', 'events_statements_summary_by_host_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_statements_summary_global_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'SCHEMA_NAME', 'performance_schema', 'events_statements_summary_by_digest', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_statements_summary_by_program', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_statements_histogram_global', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'SCHEMA_NAME', 'performance_schema', 'events_statements_histogram_by_digest', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_transactions_current', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_transactions_history', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_transactions_summary_by_thread_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'ACCOUNT', 'performance_schema', 'events_transactions_summary_by_account_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'USER', 'performance_schema', 'events_transactions_summary_by_user_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'HOST', 'performance_schema', 'events_transactions_summary_by_host_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'events_transactions_summary_global_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'USER', 'performance_schema', 'events_errors_summary_by_user_by_error', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'HOST', 'performance_schema', 'events_errors_summary_by_host_by_error', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'ACCOUNT', 'performance_schema', 'events_errors_summary_by_account_by_error', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'THREAD_ID', 'performance_schema', 'events_errors_summary_by_thread_by_error', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'ERROR_NUMBER', 'performance_schema', 'events_errors_summary_global_by_error', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'USER', 'performance_schema', 'users', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'ACCOUNT', 'performance_schema', 'accounts', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'HOST', 'performance_schema', 'hosts', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'socket_instances', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'socket_summary_by_instance', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'socket_summary_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'session_connect_attrs', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'session_account_connect_attrs', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'memory_summary_global_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'ACCOUNT', 'performance_schema', 'memory_summary_by_account_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'HOST', 'performance_schema', 'memory_summary_by_host_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'memory_summary_by_thread_by_event_name', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'USER', 'performance_schema', 'memory_summary_by_user_by_event_name', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'table_handles', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'metadata_locks', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'data_locks', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'replication_connection_configuration', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'replication_connection_status', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'replication_applier_configuration', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'replication_applier_status', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'replication_applier_status_by_coordinator', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'replication_applier_status_by_worker', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'OWNER_THREAD_ID', 'performance_schema', 'prepared_statements_instances', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'prepared_statements_instances', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'user_variables_by_thread', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'ACCOUNT', 'performance_schema', 'status_by_account', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'HOST', 'performance_schema', 'status_by_host', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'status_by_thread', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'USER', 'performance_schema', 'status_by_user', 'UNIQUE', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'global_status', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'session_status', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'variables_by_thread', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'global_variables', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'session_variables', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'persisted_variables', 'PRIMARY KEY', 'YES'),
	('def', 'performance_schema', 'PRIMARY', 'performance_schema', 'user_defined_functions', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'db', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'user', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'default_roles', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'role_edges', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'global_grants', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'password_history', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'func', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'plugin', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'name', 'mysql', 'help_topic', 'UNIQUE', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'help_topic', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'name', 'mysql', 'help_category', 'UNIQUE', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'help_category', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'help_relation', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'servers', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'tables_priv', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'columns_priv', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'name', 'mysql', 'help_keyword', 'UNIQUE', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'help_keyword', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'time_zone_name', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'time_zone', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'time_zone_transition', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'time_zone_transition_type', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'time_zone_leap_second', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'procs_priv', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'component', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'slave_relay_log_info', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'slave_master_info', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'slave_worker_info', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'gtid_executed', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'replication_asynchronous_connection_failover', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'replication_asynchronous_connection_failover_managed', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'replication_group_member_actions', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'replication_group_configuration_version', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'server_cost', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'engine_cost', 'PRIMARY KEY', 'YES'),
	('def', 'mysql', 'PRIMARY', 'mysql', 'proxies_priv', 'PRIMARY KEY', 'YES'),
	('def', 'sys', 'PRIMARY', 'sys', 'sys_config', 'PRIMARY KEY', 'YES'),
	('def', 'employes', 'PRIMARY', 'employes', 'dept', 'PRIMARY KEY', 'YES'),
	('def', 'employes', 'PRIMARY', 'employes', 'projet', 'PRIMARY KEY', 'YES'),
	('def', 'employes', 'PRIMARY', 'employes', 'emp', 'PRIMARY KEY', 'YES'),
	('def', 'employes', 'FK_DEPTNO', 'employes', 'emp', 'FOREIGN KEY', 'YES'),
	('def', 'employes', 'FK_MGR', 'employes', 'emp', 'FOREIGN KEY', 'YES'),
	('def', 'tp1', 'PRIMARY', 'tp1', 'livre', 'PRIMARY KEY', 'YES'),
	('def', 'tp1', 'PRIMARY', 'tp1', 'exemplaire', 'PRIMARY KEY', 'YES'),
	('def', 'tp1', 'FK_Livre', 'tp1', 'exemplaire', 'FOREIGN KEY', 'YES'),
	('def', 'guide', 'PRIMARY', 'guide', 'restaurants', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'categories', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'departements', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'habilitations', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'images', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'proprietaires', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'association_img', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'FK_bien_immmo', 'immochateau', 'association_img', 'FOREIGN KEY', 'YES'),
	('def', 'immochateau', 'FK_img', 'immochateau', 'association_img', 'FOREIGN KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'biens_immobiliers', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'biens_immobiliers_ibfk_1', 'immochateau', 'biens_immobiliers', 'FOREIGN KEY', 'YES'),
	('def', 'immochateau', 'biens_immobiliers_ibfk_2', 'immochateau', 'biens_immobiliers', 'FOREIGN KEY', 'YES'),
	('def', 'immochateau', 'fk_departement', 'immochateau', 'biens_immobiliers', 'FOREIGN KEY', 'YES'),
	('def', 'immochateau', 'fK_proprietaire', 'immochateau', 'biens_immobiliers', 'FOREIGN KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'documents', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'documents_ibfk_1', 'immochateau', 'documents', 'FOREIGN KEY', 'YES'),
	('def', 'immochateau', 'PRIMARY', 'immochateau', 'utilisateurs', 'PRIMARY KEY', 'YES'),
	('def', 'immochateau', 'utilisateurs_ibfk_1', 'immochateau', 'utilisateurs', 'FOREIGN KEY', 'YES'),
	('def', 'voiliers', 'PRIMARY', 'voiliers', 'utilisateurs', 'PRIMARY KEY', 'YES'),
	('def', 'voiliers', 'PRIMARY', 'voiliers', 'candidats', 'PRIMARY KEY', 'YES'),
	('def', 'festival', 'PRIMARY', 'festival', 'departements', 'PRIMARY KEY', 'YES'),
	('def', 'festival', 'PRIMARY', 'festival', 'candidats', 'PRIMARY KEY', 'YES'),
	('def', 'festival', 'Fk_departement_user', 'festival', 'candidats', 'FOREIGN KEY', 'YES');
/*!40000 ALTER TABLE `TABLE_CONSTRAINTS` ENABLE KEYS */;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
